#from pathlib import Path
import pandas as pd
#file_path = Path("just tacos and burritos.csv").absolute()
#df = pd.read_csv(str(file_path), sep=",")
df = pd.read_csv("just tacos and burritos.csv", sep=",")
# We'll use this data as our main dataset

print(df["id"])
print(df["address"])
print(df["categories"])
print(df["city"])
print(df["country"])
print(df["cuisines"])
print(df["dateAdded"])
print(df["dateUpdated"])
print(df["keys"])
print(df["latitude"])
print(df["longitude"])
print(df["menuPageURL"])
print(df["menus.amountMax"])
print(df["menus.amountMin"])
print(df["menus.category"])
print(df["menus.currency"])
print(df["menus.dateSeen"])
print(df["menus.description"])
print(df["menus.name"])
print(df["name"])
print(df["postalCode"])
print(df["priceRangeCurrency"])
print(df["priceRangeMin"])
print(df["priceRangeMax"])
print(df["province"])
print(df["websites"])
